services:
  takeatripth:
    build: .
    container_name: takeatripth
    restart: always
    ports:
      - "3005:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
